version: "2"

pipelines:
  - name: "Deploy to S3"
    trigger:
      events:
        - push

    jobs:
      - name: "Build and Deploy"
        steps:
          - name: "Checkout Repository"
            uses: actions/checkout@v2

          - name: "Setup Node.js"
            uses: actions/setup-node@v3
            with:
              node-version: "14"

          - name: "Install Dependencies"
            run: |
              npm install

          - name: "Build React App"
            run: |
              npm run build

          - name: "Deploy to S3"
            run: |
              aws s3 sync build/ s3://static-app-react
            env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AKIAUEEQUF2IKBFYMZ5N }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.MnfJ/Yt2BACky+pZbEByzw0RUZ2dvc0Uj5Iluyqz }}
              AWS_DEFAULT_REGION: "US East (N. Virginia)"
