version: "1.0"

pipelines:
  - name: "Deploy to S3"
    trigger:
      events:
        - push

    steps:
      - name: "Checkout Repository"
        checkout: {}

      - name: "Install Dependencies"
        run: |
          # Install Node.js and npm
          curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt-get install -y nodejs

          # Install project dependencies
          npm install
        envs:
          - name: "CI"
            value: "true"

      - name: "Build and Deploy to S3"
        run: |
          # Build the React app
          npm run build

          # Upload build artifacts to S3
          aws s3 sync build/ s3://static-app-react
        secrets:
          - AWS_ACCESS_KEY_ID
          - AWS_SECRET_ACCESS_KEY
        envs:
          - name: "AWS_DEFAULT_REGION"
            value: "US East (N. Virginia)"  # Replace with your AWS region

secrets:
  - name: "AWS_ACCESS_KEY_ID"
    value: "${{ secrets.AKIAUEEQUF2IKBFYMZ5N }}"
  - name: "AWS_SECRET_ACCESS_KEY"
    value: "${{ secrets.MnfJ/Yt2BACky+pZbEByzw0RUZ2dvc0Uj5Iluyqz}}"
